ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "coursePreference" TEXT,
ADD COLUMN IF NOT EXISTS "hobbies" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "sleepSchedule" TEXT,
ADD COLUMN IF NOT EXISTS "noiseTolerance" TEXT,
ADD COLUMN IF NOT EXISTS "studyHours" INTEGER,
ADD COLUMN IF NOT EXISTS "sleepHours" INTEGER;
